### PR TITLE
fix: display share based on feature availability

### LINKED ISSUE #467: Hide share action if browser does not support the WebShare APIs
**Describe the bug**
If the browser does not support the WebShare API, the share CTA does nothing.

**To Reproduce**
Go to any animal page and click on share on a browser that does not have support for share.

**Expected behavior**
Share should not be shown in such scenarios.

### PR DESCRIPTION
**Pull request by foobar98**
Fixes #467 

|Available (safari) | Unavailable (chrome) |
|-|-|
|Screenshot 2022-10-10 at 10 09 00 PM|Screenshot 2022-10-10 at 10 09 20 PM|

### CODE REVIEW

File: src/components/pets/PetInfo.tsx [hunk 1]
```diff
@@ -45,6 +45,11 @@ export default function PetInfo() {
     fetcher
   );
 
+  useEffect(() => {
+    const shareData = getShareData();
+    setEnableShare(navigator.canShare && navigator.canShare(shareData));
+  }, [pet]);
```
[the remark this answers is not in the document]
Comment (foobar98) [reply src/components/pets/PetInfo.tsx]: done

File: src/components/pets/PetInfo.tsx [hunk 2]
```diff
@@ -22,21 +23,20 @@ import Placeholder from "./placeholder-light.png";
 export default function PetInfo() {
   const { id } = useParams<string>();
   const { tokenHeaders } = usePetAuth();
+  const [enableShare, setEnableShare] = useState(false);
 
-  function handleShare() {
-    const shareData = {
+  const getShareData = () => {
```
Comment (redxzeta) [inline src/components/pets/PetInfo.tsx:28]: looks like more lint issues here

Comment (foobar98) [reply src/components/pets/PetInfo.tsx]: ahh, done

**Review by redxzeta — APPROVED** [review]
